In [12]:
import pandas as pd 
import matplotlib.pyplot as plt

In [13]:
# Read the dataset 
df = pd.read_csv('./dataset/FakeNewsNet.csv')

## Quick look at the Data Structure

* **Title** - Title of the article
* **News_url** - URL of the article
* **Source domain** - Web domain where article was posted.
* **Tweet_num** - number of retweets for this article.
* **Real** - label column, where 1 is real and 0 is fake.

In [14]:
df.head(3)

,title,news_url,source_domain,tweet_num,real
0,Kandi Burruss Explodes Over Rape Accusation on...,http://toofab.com/2017/05/08/real-housewives-a...,toofab.com,42,1
1,People's Choice Awards 2018: The best red carp...,https://www.today.com/style/see-people-s-choic...,www.today.com,0,1
2,Sophia Bush Sends Sweet Birthday Message to 'O...,https://www.etonline.com/news/220806_sophia_bu...,www.etonline.com,63,1

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 23196 entries, 0 to 23195
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   title          23196 non-null  str
 1   news_url       22866 non-null  str
 2   source_domain  22866 non-null  str
 3   tweet_num      23196 non-null  int64
 4   real           23196 non-null  int64
dtypes: int64(2), str(3)
memory usage: 906.2 KB

In [16]:
df.drop(columns=['news_url'], inplace=True)

In [17]:
df.isnull().sum()

title              0
source_domain    330
tweet_num          0
real               0
dtype: int64

In [18]:
# Remove nan rows
df.dropna(axis=0, inplace=True)

In [19]:
df.describe()

          tweet_num          real
count  22866.000000  22866.000000
mean      88.398802      0.759687
std      488.712092      0.427283
min        0.000000      0.000000
25%       11.000000      1.000000
50%       38.000000      1.000000
75%       65.000000      1.000000
max    29060.000000      1.000000

In [20]:
print(f'Total of duplicated rows: {df.duplicated().sum()}')

df.drop_duplicates(inplace=True)

Total of duplicated rows: 168

In [21]:
df.info()

<class 'pandas.DataFrame'>
Index: 22698 entries, 0 to 23195
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   title          22698 non-null  str
 1   source_domain  22698 non-null  str
 2   tweet_num      22698 non-null  int64
 3   real           22698 non-null  int64
dtypes: int64(2), str(2)
memory usage: 886.6 KB

## Creating a test set

In [22]:
from sklearn.model_selection import train_test_split

train_test, test_set = train_test_split(
    df, test_size=0.2, random_state=42, stratify=df['real']
)